version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
    - 3000:3000
    environment:
    - NODE_ENV=development
    - PORT=3000
    - REDIS_URL=redis://redis
    depends_on:
    - redis

  redis:
    image: redis
    ports:
    - 6379:6379
