FROM node:10-alpine
RUN apk add --no-cache docker
RUN apk add --no-cache git
RUN apk add --no-cache openssh
RUN npm install -g semantic-release
RUN npm install -g @semantic-release/changelog
RUN npm install -g semantic-release-docker
