version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
    - 8080:8080
    environment:
    - NODE_ENV=production
    - PORT=8080
    - REDIS_URL=redis://redis
    depends_on:
    - redis

  redis:
    image: redis
    container_name: redis
    ports:
    - 127.0.0.1:6379:6379
    expose:
    - 6379
