# Manifest for deploying to Kubernetes
apiVersion: v1
kind: Namespace
metadata:
  name: maelstrom
---
apiVersion: v1
kind: Service
metadata:
  name: maelstrom
  namespace: maelstrom
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: maelstrom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maelstrom
  namespace: maelstrom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maelstrom
  template:
    metadata:
      labels:
        app: maelstrom
    spec:
      containers:
      - name: maelstrom
        image: jftanner/maelstrom
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: maelstrom-ingress
  namespace: maelstrom
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - maelstrom.tanndev.com
    secretName: maelstrom-tls
  rules:
  - host: maelstrom.tanndev.com
    http:
      paths:
      - backend:
          serviceName: maelstrom
          servicePort: 80
